name: Backend deployment via Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      # - name: Set up Python environment
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.10"

      # - name: Install Heroku CLI
      #   run: |
      #     curl https://cli-assets.heroku.com/install.sh | sh

      # - name: Deploy to Heroku
      #   uses: akhileshns/heroku-deploy@v3.12.14
      #   with:
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
      #     heroku_email: ${{ secrets.HEROKU_EMAIL }}
      #     branch: main
      #     appdir: backend

      # - name: Show git remotes
      #   run: git remote -v

      # - name: Test Heroku login
      #   run: heroku auth:whoami
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
